// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm97RbYw6JuL9d_jJlFWSC-QxtzJScNEs',
    appId: '1:423482815037:web:caa3d5e544b256a4bcb054',
    messagingSenderId: '423482815037',
    projectId: 'jalals-outer-space-78978',
    authDomain: 'jalals-outer-space-78978.firebaseapp.com',
    storageBucket: 'jalals-outer-space-78978.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzzhmsv5SwUxgYxibrRnJmvsrG3gVvGPg',
    appId: '1:423482815037:android:150e7ae90f95afa9bcb054',
    messagingSenderId: '423482815037',
    projectId: 'jalals-outer-space-78978',
    storageBucket: 'jalals-outer-space-78978.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW0upaf7oR6YI4bRlmabCJAmnMTSDk6jw',
    appId: '1:423482815037:ios:f680bc92c07ec193bcb054',
    messagingSenderId: '423482815037',
    projectId: 'jalals-outer-space-78978',
    storageBucket: 'jalals-outer-space-78978.firebasestorage.app',
    iosBundleId: 'com.jdev.myspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW0upaf7oR6YI4bRlmabCJAmnMTSDk6jw',
    appId: '1:423482815037:ios:f680bc92c07ec193bcb054',
    messagingSenderId: '423482815037',
    projectId: 'jalals-outer-space-78978',
    storageBucket: 'jalals-outer-space-78978.firebasestorage.app',
    iosBundleId: 'com.jdev.myspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm97RbYw6JuL9d_jJlFWSC-QxtzJScNEs',
    appId: '1:423482815037:web:f8b2a3f626757a52bcb054',
    messagingSenderId: '423482815037',
    projectId: 'jalals-outer-space-78978',
    authDomain: 'jalals-outer-space-78978.firebaseapp.com',
    storageBucket: 'jalals-outer-space-78978.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey:
        'AIzaSyAm97RbYw6JuL9d_jJlFWSC-QxtzJScNEs', // انسخ نفس القيم الموجودة في قسم web في الأسفل
    appId: '1:423482815037:web:caa3d5e544b256a4bcb054',
    messagingSenderId: '423482815037',
    projectId: 'jalals-outer-space-78978',
    authDomain: 'jalals-outer-space-78978.firebaseapp.com',
    storageBucket: 'jalals-outer-space-78978.firebasestorage.app',
  );
}